name: rusht
description: "A rental marketplace application connecting renters and owners"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  image_picker: ^1.0.5
  flutter_secure_storage: ^9.0.0
  http: ^1.1.2
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  go_router: ^14.6.2
  flutter_dotenv: ^5.1.0
  cloudinary_public: ^0.23.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  remixicon: ^1.0.0
  uuid: ^4.3.3
  timeago: ^3.7.0
  supabase_flutter: ^2.8.2
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0
  email_validator: ^2.1.17
  google_fonts: ^6.2.1
  # Camera and Image Processing
  camera: ^0.10.5+5
  image: ^4.1.3
  photo_view: ^0.14.0
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_text_recognition: ^0.11.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  intl_translation: ^0.20.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env
